
fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        args: [--style=Google]
      - id: clang-tidy
      - id: oclint
      - id: uncrustify
      - id: cppcheck
      - id: cpplint
      - id: include-what-you-use
# repos:
# -   repo: https://github.com/cheshirekow/cmake-format-precommit
#     rev: v0.6.13
#     hooks:
#     -   id: cmake-format
#     -   id: cmake-lint
# -   repo: https://github.com/pocc/pre-commit-hooks
#     rev: v1.3.5
#     hooks:
#     -   id: clang-format
#         # args: [--style=Google, -i]
# -   repo: https://github.com/cheshirekow/cmake-format-precommit
#     rev: v0.6.13
#     hooks:
#     -   id: cmake-format
#     -   id: cmake-lint

