// MAIN GAME SETTINGS
#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 1024
#define GAME_SPEED 20


// PATHS ETC.
#define ASSET_PATH "../assets"
#define BRICK_ASSET_PATH ASSET_PATH  "/brick.png"
#define FLOOR_ASSET_PATH ASSET_PATH  "/floor.png"

#define MARIO_ASSET_PREPATH ASSET_PATH "/mario"
#define MARIO_1 MARIO_ASSET_PREPATH "1.png"
#define MARIO_2 MARIO_ASSET_PREPATH "2.png"
#define MARIO_3 MARIO_ASSET_PREPATH "3.png"
#define MARIO_4 MARIO_ASSET_PREPATH "4.png"
#define MARIO_5 MARIO_ASSET_PREPATH "5.png"
#define MARIO_6 MARIO_ASSET_PREPATH "6.png"
#define MARIO_7 MARIO_ASSET_PREPATH "7.png"


// SPRITE DIMENSIONS
#define FLOOR_WIDTH 1024
#define FLOOR_HEIGHT 62

#define MARIO_WIDTH 66
#define MARIO_HEIGHT 88


// BACKROUND POSITIONS
#define FLOOR_X 0
#define FLOOR_Y WINDOW_HEIGHT - FLOOR_HEIGHT

// CHARACTER RELATED DEFINITIONS
#define HEADING_LEFT 1
#define HEADING_RIGHT 2
#define FLOOR_INTERACTION_TRESHOLD 5
#define GRAVITY_COEFFICIENT 2

// MARIO DYNAMICS
#define MARIO_STEP_SIZE 10
#define MARIO_JUMP_STEP_SIZE 4
#define MARIO_LATERAL_RIGHT_SPEED 4
#define MARIO_LATERAL_LEFT_SPEED -4
#define MARIO_JUMP_SPEED -16